[project]
name = "fastapi-crud-db-auth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.2",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.40.0",
]
